variables:
  DH_REPOSITORY: zammad

github:
  tags:
    - deploy
  script:
    - scripts/sync_repo.sh git@github.com:zammad/zammad-docker.git

build_image:
  tags:
    - core
  only:
    - master
    - develop
    - tags
  script:
    - docker info
    - scripts/build_image.sh
